"""Added board

Revision ID: df5e4f3fb07b
Revises: 941ebe9ca560
Create Date: 2022-06-18 11:46:58.938695

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'df5e4f3fb07b'
down_revision = '941ebe9ca560'
branch_labels = None
depends_on = None


statuses = sa.Enum('in_progress', 'finished', 'dropped', name='statuses')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('board', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('player1_stack', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('player2_stack', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', statuses, server_default='in_progress', nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player2_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    statuses.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
