# Generated by Django 3.2 on 2022-05-29 09:26

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_player1_turn', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boards1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boards2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
