# Generated by Django 3.2 on 2022-05-29 11:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220529_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='player1_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='board',
            name='player2_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.JSONField(),
        ),
    ]
