# Generated by Django 3.2 on 2022-05-31 07:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220531_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_player1_ai',
            field=models.BooleanField(default=True),
        ),
    ]
